name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Restore dependencies and build
        run: |
          npm ci
          npm run build

      - name: Get short commit SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: myrodlbot.${{ steps.short-sha.outputs.sha }}.CI
          path: dist/